openapi: 3.0.0
info:
  title: Sender
  description: Allows to send messages using different canals (email, SMS, messenger)
  contact:
    email: darthtyranus666666@gmail.com
  license:
    name: MIT
  version: 1.0.0
servers:
- url: /v1
  description: first api version
paths:
  /mail:
    post:
      summary: send email containing change data
      operationId: mail
      requestBody:
        description: necessary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mail'
        required: true
      responses:
        200:
          description: successful send
        400:
          description: bad input parameters
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Mail:
      required:
      - html_content
      - recipients
      - subject
      - data
      type: object
      properties:
        recipients:
          type: array
          items:
            type: string
        html_content:
          type: string
        subject:
          type: string
        data:
          $ref: '#/components/schemas/Data'
      example:
        recipients:
        - darthtyranus666666@gmail.com
        - john@doe.com
    Data:
      required:
      - url
      - attachments
      type: object
      properties:
        url:
          type: string
          example: URL of the page which content was changed
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
      example:
        url: https://github.com
        diff: base64 encoded png
        real_diff: base64 encoded png
    Attachment:
      required:
      - content
      - filename
      - filetype
      type: object
      properties:
        filename:
          type: string
          example: picture.png
        content:
          type: string
          example: base64 encoded data
        filetype:
          type: string
          example: data type such as image/png
