apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-api
  namespace: monitor-page
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - monitor.example.url
    secretName: front-monitor-base-tls
  rules:
  - host: monitor.example.url
    http:
      paths:
        - path: /
          backend:
            serviceName: front
            servicePort: 80
