apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: manager-api
  namespace: monitor-page
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.monitor.example.url
    secretName: api-monitor-base-tls
  rules:
  - host: api.monitor.example.url
    http:
      paths:
        - path: /
          backend:
            serviceName: manager
            servicePort: 8000
