apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: monitor-page
spec:
  selector:
    matchLabels:
      app: manager
  replicas: 1
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: master
        image: registry.example.url/d0ku/monitor_page_manager:%LATEST_HASH%
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 40m
            memory: 40Mi
          limits:
            cpu: 300m
            memory: 300Mi
        env:
        - name: APP_URL
          value: https://api.monitor.example.url
        - name: FRONT_URL
          value: https://monitor.example.url
        - name: ALLOWED_ORIGIN
          value: "*"
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: secret-jwt
              key: jwt-secret
        - name: SENDER_API
          value: "http://sender.monitor-page.svc.cluster.local:8080"
        - name: DATABASE_TYPE
          value: "postgres"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: monitor.monitor-page-db.credentials
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: monitor.monitor-page-db.credentials
              key: password
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_HOST
          value: "monitor-page-db.monitor-page.svc.cluster.local"
        - name: DATABASE_DB_NAME
          value: "monitor"
      imagePullSecrets:
      - name: regcred
