apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  namespace: monitor-page
spec:
  selector:
    matchLabels:
      app: sender
  replicas: 2
  template:
    metadata:
      labels:
        app: sender
    spec:
      nodeSelector:
        workHorse: "yes"
      containers:
      - name: master
        ports:
        - containerPort: 8080
        image: registry.example.url/d0ku/monitor_page_sender:%LATEST_HASH%
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: secret-sendgrid
              key: api-key
        - name: MAIL_SENDER
          value: monitor@example.url
      imagePullSecrets:
      - name: regcred
