apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitor-page.fullname" . }}-comparator
spec:
  selector:
    matchLabels:
      {{- include "monitor-page.selectorLabels" . | nindent 6 }}
      app: comparator
  {{- if not .Values.comparator.autoscaling.enabled }}
  replicas: {{ .Values.comparator.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "monitor-page.selectorLabels" . | nindent 8 }}
        app: comparator
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.comparator.securityContext | nindent 12 }}
          image: "{{ .Values.manager.image.repository | default (printf "%s/d0ku/monitor-page_comparator" .Values.baseRegistry) }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.comparator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/live
              port: http
          readinessProbe:
            httpGet:
              path: /v1/ready
              port: http
          resources:
            {{- toYaml .Values.comparator.resources | nindent 12 }}
      {{- with .Values.comparator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.comparator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.comparator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
