name: Automatic Rebase
on:
  issue_comment:
    types: [ created ]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body,
      '/rebase') && github.event.comment.author_association == 'OWNER'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@c473b716e3fcde0c6bf67416e2c2882830ad40f6 # pin@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
