name: Automatic Rebase
on:
  issue_comment:
    types: [ created ]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body,
      '/rebase') && github.event.comment.author_association == 'MEMBER'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@7cea12ac34ab078fa37e87798d8986185afa7bf2 # pin@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
