name: single-docker-publish

on:
  workflow_dispatch:
    inputs:
      imageSuffix:
        required: true
      # TODO: change to support multiple tags at once
      imageTag:
        required: true
        default: 'latest'
      # Platforms have to be comma separated
      imagePlatforms:
        required: false
        default: 'linux/amd64'
      repoRef:
        required: true
        default: 'master'
      imageBase:
        required: false
        default: 'ghcr.io/${{ github.repository_owner }}/monitor-page-'
      imageRepository:
        required: false
        default: 'ghcr.io'

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.repoRef }}

      -
        name: Set up variables
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          IMAGE_NAME=$(echo ${{ github.event.inputs.imageBase }}${{ github.event.inputs.imageSuffix }} | tr '[A-Z]' '[a-z]')
          IMAGE_ID="${{ github.event.inputs.imageRepository }}/$IMAGE_NAME"

          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-${{ github.event.inputs.repoRef }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ env.IMAGE_NAME }}-

      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.event.inputs.imageSuffix }}
          platforms: ${{ github.event.inputs.imagePlatforms }}
          push: true
          tags: |
            ${{ env.IMAGE_ID }}:${{ github.event.inputs.imageTag }}
            ${{ env.IMAGE_ID }}:${{ github.event.inputs.repoRef }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
